# Generated by Django 4.2 on 2023-04-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0002_alter_brand_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
